keys:
  - &host_tahani ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMDSdANMtom1GIuSxVF0NQKjjpvjxjLzRAFWY8u8/Jxo
  - &host_michael ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAl0KvNGk1nh4KoExP4DiQjePfrtOIFG0UkfSBW/lYbY
  - &host_jason age1ez6j3r5wdp0tjy7n5qzv5vfakdc2nh2zeu388zu7a80l0thv052syxq5e2
  - &host_chidi age1tlymdmaukhwupzrhszspp26lgd8s64rw4vu9lwc7gsgrjm78095s9fe9l3
creation_rules:
  - path_regex: secrets/[^/]+$
    key_groups:
      - age:
        - *host_tahani
        - *host_michael
        - *host_jason
        - *host_chidi
