keys:
  - &user_cschmatzler age1xate984yhl9qk9d4q99pyxmzz48sq56nfhu8weyzkgum4ed5tc5shjmrs7
  - &host_tahani age1njjegjjdqzfnrr54f536yl4lduqgna3wuv7ef6vtl9jw5cju0grsgy62tm
  - &host_janet age1f9h725ewwwwwkelnrvdvrurg6fcsn3zxrxdt0v6v8ys0nzngcsvqu77nc8
  - &host_chidi age1ft00p4grrnzupqj9ln23jdn78wf5j9dz8q9t8dt7tsxuvh77nszqnkx0e6
creation_rules:
  - path_regex: secrets/[^/]+$
    key_groups:
      - age:
        - *user_cschmatzler
        - *host_tahani
        - *host_janet
        - *host_chidi
