import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const messages = [
  // Short
  "Schlepping...",
  "Combobulating...",
  "Doing...",
  "Channelling...",
  "Vibing...",
  "Concocting...",
  "Spelunking...",
  "Transmuting...",
  "Imagining...",
  "Pontificating...",
  "Whirring...",
  "Cogitating...",
  "Honking...",
  "Flibbertigibbeting...",
  "Noodling...",
  "Percolating...",
  "Ruminating...",
  "Simmering...",
  "Marinating...",
  "Fermenting...",
  "Gestating...",
  "Hatching...",
  "Brewing...",
  "Steeping...",
  "Contemplating...",
  "Musing...",
  "Pondering...",
  "Mulling...",
  "Daydreaming...",
  "Woolgathering...",
  "Dithering...",
  "Faffing...",
  "Puttering...",
  "Tinkering...",
  "Fiddling...",
  "Noodging...",
  "Finagling...",
  "Wrangling...",
  "Jiggling...",
  "Wiggling...",
  "Shimmying...",
  "Galumphing...",
  "Perambulating...",
  "Meandering...",
  "Traipsing...",
  "Moseying...",
  "Sauntering...",
  "Ambling...",
  "Pottering...",
  "Bumbling...",
  "Futzing...",
  "Schmalzing...",
  "Kerfuffling...",
  "Bamboozling...",
  "Discombobulating...",
  "Recombobulating...",
  "Unbefuddling...",
  "Defenestrating...",
  "Confabulating...",
  "Persnicketing...",
  "Flummoxing...",
  "Befuddling...",
  "Snorkeling...",
  "Yodeling...",
  "Zigzagging...",
  "Ricocheting...",
  "Somersaulting...",
  "Pirouetting...",
  "Canoodling...",
  "Schmoozing...",
  "Kibbitzing...",
  "Skedaddling...",
  "Scampering...",
  "Skittering...",
  "Sashaying...",
  "Swashbuckling...",
  "Oscillating...",
  "Undulating...",
  "Pulsating...",
  "Effervescing...",
  "Fizzing...",
  "Bubbling...",
  "Perplexing...",
  "Mystifying...",
  "Enchanting...",
  "Bewitching...",
  "Beguiling...",
  "Mesmerizing...",
  "Bedazzling...",
  "Sparkling...",
  "Glittering...",
  "Scintillating...",
  "Coruscating...",
  "Phosphorescing...",
  "Luminescing...",
  "Sublimating...",
  "Synthesizing...",
  "Amalgamating...",
  "Procrastinating...",
  "Dillydallying...",
  "Lollygagging...",
  "Dawdling...",
  "Malingering...",
  "Skulking...",
  "Lurking...",
  "Sleuthing...",
  "Rummaging...",
  "Fossicking...",
  "Foraging...",
  "Scavenging...",
  "Absquatulating...",
  "Vamoosing...",
  "Absconding...",
  "Grooving...",
  "Jamming...",
  "Improvising...",
  "Extemporizing...",
  "Freestyling...",
  "Frolicking...",
  "Gamboling...",
  "Blorping...",
  "Flonking...",
  "Snurfling...",
  "Whomping...",
  "Zorping...",
  "Biffing...",
  "Splunging...",
  "Thwacking...",
  "Gonkulating...",
  "Splorfing...",
  "Wibbling...",
  "Wobbling...",
  "Squonking...",
  "Plonking...",
  "Bonking...",
  "Zonking...",
  "Flumping...",
  "Clomping...",
  "Squelching...",
  "Schlurping...",
  "Glurping...",
  "Burbling...",
  "Gurgling...",
  "Splooshing...",
  "Whooshing...",
  "Swooshing...",
  "Kerplunking...",
  "Thunking...",
  "Clunking...",
  "Clanking...",
  "Rattling...",
  "Jostling...",
  "Rustling...",
  "Bustling...",
  "Hustling...",
  "Miffing...",
  "Boffing...",
  "Snazzifying...",
  "Pizzazzing...",
  "Razzmatazzing...",
  "Bedoodling...",
  "Doodling...",
  "Scribbling...",
  "Squiggling...",
  "Wriggling...",
  "Higgling...",
  "Piggling...",
  "Figgling...",
  "Gibbering...",
  "Jabbering...",
  "Blathering...",
  "Blithering...",
  "Withering...",
  "Slithering...",
  "Tethering...",
  "Feathering...",
  "Weathering...",
  "Leathering...",
  "Heathering...",
  "Smoldering...",
  "Moldering...",
  "Shouldering...",
  "Bouldering...",
  "Tottering...",
  "Teetering...",
  "Tittering...",
  "Flittering...",
  "Jittering...",
  "Frittering...",
  "Twittering...",
  "Nattering...",
  "Chattering...",
  "Clattering...",
  "Splattering...",
  "Battering...",
  "Scattering...",
  "Shattering...",
  "Flattering...",
  "Pattering...",
  "Tattering...",
  "Mattering...",
  "Yammering...",
  "Hammering...",
  "Stammering...",
  "Clamoring...",
  "Glamoring...",
  "Enamoring...",
  "Shimmering...",
  "Glimmering...",
  "Brimming...",
  "Skimming...",
  "Trimming...",
  "Primming...",
  "Whimming...",
  "Humming...",
  "Strumming...",
  "Thrumming...",
  "Drumming...",
  "Plumbing...",
  "Thumbing...",
  "Numbing...",
  "Fumbling...",
  "Grumbling...",
  "Mumbling...",
  "Rumbling...",
  "Stumbling...",
  "Tumbling...",
  "Crumbling...",
  "Jumbling...",
  "Humbling...",
  "Bungling...",
  "Jungling...",
  "Mangling...",
  "Wangling...",
  "Dangling...",
  "Tangling...",
  "Jangling...",
  "Angling...",
  "Strangling...",
  "Mingling...",
  "Tingling...",
  "Jingling...",
  "Singling...",
  "Ringling...",
  "Kingling...",
  "Tokenmaxxing...",

  // Long
  "Consulting the void...",
  "Asking the electrons...",
  "Bribing the compiler...",
  "Negotiating with entropy...",
  "Whispering to the bits...",
  "Tickling the stack...",
  "Massaging the heap...",
  "Appeasing the garbage collector...",
  "Summoning semicolons...",
  "Herding pointers...",
  "Untangling spaghetti...",
  "Polishing the algorithms...",
  "Waxing philosophical...",
  "Consulting ancient scrolls...",
  "Reading tea leaves...",
  "Shaking the magic 8-ball...",
  "Sacrificing to the demo gods...",
  "Warming up the hamsters...",
  "Spinning up the squirrels...",
  "Caffeinating...",
  "Existentially questioning...",
  "Having a little think...",
  "Stroking chin thoughtfully...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Transcending mere computation...",
  "Ascending to a higher plane...",
  "Communing with the machine spirit...",
  "Performing arcane rituals...",
  "Invoking elder functions...",
  "Consulting the oracle...",
  "Divining the answer...",
  "Scrying the codebase...",
  "Dowsing for bugs...",
  "Rearranging deck chairs...",
  "Shuffling bits around...",
  "Aligning the chakras...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Calibrating the flux capacitor...",
  "Charging the crystals...",
  "Tuning the vibrations...",
  "Adjusting the cosmic frequency...",
  "Waiting for a sign...",
  "Hoping for the best...",
  "Manifesting solutions...",
  "Willing it into existence...",
  "Believing really hard...",
  "Politely asking the CPU...",
  "Bribing the runtime...",
  "Flirting with the database...",
  "Sweet-talking the API...",
  "Negotiating with deadlines...",
  "Having words with the cache...",
  "Reasoning with the memory...",
  "Pleading with the logs...",
  "Bargaining with fate...",
  "Making offerings to the CI...",
  "Praying to the uptime gods...",
  "Consulting the rubber duck...",
  "Interrogating the stack trace...",
  "Cross-examining the debugger...",
  "Petitioning the kernel...",
  "Lobbying the scheduler...",
  "Schmoozing the network...",
  "Buttering up the firewall...",
  "Wining and dining the servers...",
  "Taking the bytes out for lunch...",
  "Giving the code a pep talk...",
  "Reading the room...",
  "Checking under the hood...",
  "Kicking the tires...",
  "Shaking loose the cobwebs...",
  "Dusting off the neurons...",
  "Greasing the gears...",
  "Oiling the cogs...",
  "Winding up the clockwork...",
  "Stoking the furnace...",
  "Feeding the machine...",
  "Watering the logic tree...",
  "Pruning the decision branches...",
  "Harvesting the outputs...",
  "Planting computational seeds...",
  "Nurturing the algorithm...",
  "Raising the exceptions...",
  "Taming wild pointers...",
  "Herding cats in memory...",
  "Teaching old code new tricks...",
  "Whispering sweet nothings to the compiler...",
  "Serenading the syntax...",
  "Dancing with dependencies...",
  "Waltzing through the codebase...",
  "Tangoing with type errors...",
  "Doing the deployment dance...",
  "Having a moment of clarity...",
  "Experiencing a flash of insight...",
  "Channeling the ancient developers...",
  "Receiving transmissions from the cloud...",
  "Asking the hamsters to run faster...",
  "Convincing the pixels to cooperate...",
  "Teaching electrons new tricks...",
  "Bribing the byte fairies...",
  "Whispering passwords to the void...",
  "Negotiating with cosmic rays...",
  "Flattering the floating points...",
  "Seducing the semicolons...",
  "Wooing the while loops...",
  "Charming the curly braces...",
  "Hypnotizing the hash tables...",
  "Mesmerizing the memory banks...",
  "Enchanting the error handlers...",
  "Bewitching the boolean logic...",
  "Spellbinding the stack frames...",
  "Hexing the hexadecimals...",
  "Jinxing the JSON parsers...",
  "Cursing the cache misses...",
  "Blessing the build process...",
  "Anointing the algorithms...",
  "Consecrating the callbacks...",
  "Sanctifying the source code...",
  "Exorcising the exceptions...",
  "Purifying the parameters...",
  "Cleansing the closures...",
  "Baptizing the binary...",
  "Absolving the abstractions...",
  "Redeeming the recursion...",
  "Forgiving the for loops...",
  "Pardoning the pointers...",
  "Liberating the lambdas...",
  "Emancipating the enums...",
  "Freeing the functions...",
  "Releasing the references...",
  "Unbinding the variables...",
  "Untying the type knots...",
  "Unraveling the regex...",
  "Decoding the mysteries...",
  "Cracking the conundrums...",
  "Solving the riddles of RAM...",
  "Unlocking the secrets of silicon...",
  "Discovering hidden semicolons...",
  "Unearthing buried bugs...",
  "Excavating ancient APIs...",
  "Archeologically analyzing the architecture...",
  "Fossil hunting in the functions...",
  "Spelunking through the stack...",
  "Scuba diving in the data...",
  "Snorkeling through the streams...",
  "Parasailing past the parameters...",
  "Hang gliding through the heap...",
  "Bungee jumping into the backend...",
  "Skydiving through the source...",
  "Surfing the syntax waves...",
  "Skateboarding down the stack trace...",
  "Snowboarding through the schemas...",
  "Mountain climbing the modules...",
  "Hiking through the headers...",
  "Trekking through the trees...",
  "Backpacking through the binaries...",
  "Camping in the codebase...",
  "Glamping in the globals...",
  "Picnicking with the processes...",
  "Barbecuing the bugs...",
  "Roasting the race conditions...",
  "Grilling the glitches...",
  "Sautéing the syntax errors...",
  "Flambéing the failures...",
  "Caramelizing the callbacks...",
  "Braising the breakpoints...",
  "Poaching the pointers...",
  "Blanching the branches...",
  "Searing the segments...",
  "Smoking the subroutines...",
  "Curing the code smells...",
  "Pickling the packages...",
  "Preserving the protocols...",
  "Canning the constants...",
  "Bottling the buffers...",
  "Jarring the JavaScript...",
  "Decanting the data structures...",
  "Aerating the arrays...",
  "Letting the logic breathe...",
  "Aging the algorithms gracefully...",
  "Maturing the methods...",
  "Ripening the results...",
  "Seasoning the solutions...",
  "Spicing up the specs...",
  "Garnishing the getters...",
  "Plating the output nicely...",
  "Presenting with pizzazz...",
  "Adding a dash of elegance...",
  "Sprinkling some magic dust...",
  "Drizzling debug sauce...",
  "Folding in the features...",
  "Whisking the widgets...",
  "Kneading the namespaces...",
  "Rolling out the runtime...",
  "Proofing the promises...",
  "Letting the dough rise...",
  "Baking at 350 kilobytes...",
  "Frosting the functions...",
  "Decorating the deployment...",
  "Icing the interfaces...",
  "Glazing the graphics...",
  "Topping with tests...",
  "Cherry-picking the commits...",
  "Slop forking open source...",
  "Consulting the Nix oracle...",
  "Petting the derivations...",
  "Polishing the flake...",
  "Untangling the dependency pretzel...",
  "Forming a committee of rubber ducks...",
  "Checking whether the bug is load-bearing...",
  "Sending a strongly worded memo to entropy...",
  "Making impossible states feel unwelcome...",
  "Replacing TODOs with character development...",
  "Raising a tiny flag on the call stack...",
  "Refactoring the vibes...",
  "Applying artisanal determinism...",
  "Running on hopes and cache hits...",
  "Searching the sofa cushions for context...",
  "Trying turning it off and on conceptually...",
  "Looking busy in O(n log n)...",
] as const;

const readingMessages = [
  "Consulting the sacred texts...",
  "Reading between the line numbers...",
  "Borrowing the librarian's monocle...",
] as const;

const writingMessages = [
  "Putting pixels to parchment...",
  "Freshly minting a file...",
  "Teaching the disk a new story...",
] as const;

const editingMessages = [
  "Moving commas with tweezers...",
  "Performing keyhole surgery on the code...",
  "Applying a tasteful patch...",
] as const;

const shellMessages = [
  "Poking the shell with a velvet stick...",
  "Summoning a well-behaved subprocess...",
  "Asking the terminal nicely...",
] as const;

const searchingMessages = [
  "Releasing the search ferrets...",
  "Following a suspicious breadcrumb...",
  "Dusting the codebase for fingerprints...",
] as const;

const herdingMessages = [
  "Rallying the herd...",
  "Counting agents before they hatch...",
  "Passing notes between tiny terminals...",
] as const;

const toolMessages = [
  "Deploying the tool gnomes...",
  "Handing this to a tiny specialist...",
  "Pulling the correct lever...",
] as const;

const mishapMessages = [
  "That lever was apparently load-bearing...",
  "Encountering an unexpected banana peel...",
  "The machine spirit requests a do-over...",
  "One of the gnomes dropped a wrench...",
] as const;

const pepTalks = [
  "The rubber duck has reviewed the plan and nods solemnly. 🦆",
  "Your abstractions are wearing sensible shoes today. ✨",
  "This branch has excellent vibes. 🌿",
  "A wild solution is approaching. Remain calm. 🌟",
  "The compiler fears your clarity. ⚡",
  "The council of semicolons believes in you. 🪄",
  "Your next cache hit has already been foretold. 🔮",
] as const;

function pickRandom(values: readonly string[] = messages): string {
  const index = Math.floor(Math.random() * values.length);
  return values[index] ?? "Recombobulating...";
}

function messagesForTool(toolName: string): readonly string[] {
  switch (toolName) {
    case "read":
      return readingMessages;
    case "write":
      return writingMessages;
    case "edit":
      return editingMessages;
    case "bash":
      return shellMessages;
    case "grep":
    case "find":
    case "ls":
      return searchingMessages;
    case "herdr_layout":
    case "herdr_pane":
    case "herdr_agent":
      return herdingMessages;
    default:
      return toolMessages;
  }
}

function installStardust(ctx: ExtensionContext): void {
  ctx.ui.setWorkingIndicator({
    frames: [
      ctx.ui.theme.fg("dim", "·"),
      ctx.ui.theme.fg("muted", "✧"),
      ctx.ui.theme.fg("accent", "✦"),
      ctx.ui.theme.fg("muted", "✧"),
    ],
    intervalMs: 140,
  });
}

function resetWorkingDisplay(ctx: ExtensionContext): void {
  ctx.ui.setWorkingMessage();
  ctx.ui.setWorkingIndicator();
}

/** Adds playful, context-aware working messages and a little stardust to Pi. */
export default function whimsical(pi: ExtensionAPI): void {
  pi.on("session_start", (_event, ctx) => {
    installStardust(ctx);
  });

  pi.on("turn_start", (_event, ctx) => {
    installStardust(ctx);
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("tool_execution_start", (event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom(messagesForTool(event.toolName)));
  });

  pi.on("tool_execution_end", (event, ctx) => {
    if (!event.isError) return;
    ctx.ui.setWorkingMessage(pickRandom(mishapMessages));
  });

  pi.on("agent_settled", (_event, ctx) => {
    ctx.ui.setWorkingMessage();
  });

  pi.on("session_shutdown", (_event, ctx) => {
    resetWorkingDisplay(ctx);
  });

  pi.registerCommand("whimsy", {
    description: "Receive a tiny, unreasonably confident pep talk",
    handler: async (_args, ctx) => {
      ctx.ui.notify(pickRandom(pepTalks), "info");
    },
  });
}
